extends: MH0386
pull_request_rules:
  - name: Automatically queue valid Python Dependency Updates
    conditions:
      - files ~= ^(uv.lock|pyproject.toml)$
      - author = renovate[bot]
      - and:
          - check-success = Run Tests
          - check-success = Check Jupyter Notebooks
          - check-success = Check Dependency Compatibility
          - check-success = Clean Jupyter Notebooks
    actions:
      queue:
queue_rules:
  - name: default
    update_method: merge
    allow_queue_branch_edit: true
    queue_branch_merge_method: fast-forward
    queue_conditions:
      - and:
          - "check-success = DeepSource: Secrets"
          - "check-success = DeepSource: Python"
          - check-success = GitGuardian Security Checks
          - check-success = CodeRabbit
