extends: MH0386
pull_request_rules:
  - name: Automatically queue valid Python Dependency Updates
    conditions:
      - files ~= ^(uv.lock|pyproject.toml)$
      - author = renovate[bot]
      - and:
          - check-success = Test
          - check-success = Check Jupyter Notebooks
          - check-success = Check Dependency Compatibility
          - check-success = Clean Jupyter Notebooks
          - "check-success = DeepSource: Python"
    actions:
      queue:
