name: 'Setup UV'
description: 'Reusable set of steps to Setup UV'
runs:
  using: "composite"
  steps:
    - name: Restore uv cache
      uses: actions/cache@v4
      with:
        path: |
          /tmp/.uv-cache
          ${{ github.workspace }}/.venv
        key: uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
        restore-keys: |
          uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
          uv-${{ runner.os }}
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      id: uv
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"
        activate-environment: true
    - name: Install the project
      shell: bash
      if: steps.uv.outputs.cache-hit != 'true'
      run: uv sync --frozen
