name: Code Analysis
on:
  push:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  spelling:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v4
      - name: Setup UV
        uses: ./.github/actions/uv
      - name: Run typos
        run: uv run typos . --config ./pyproject.toml
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v4
      - name: Setup UV
        uses: ./.github/actions/uv
      - name: Run Ruff
        run: uv run ruff check .
  ty:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v4
      - name: Setup UV
        uses: ./.github/actions/uv
      - name: Run Pyright
        run: uv run ty check
